version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: mysecretpassword
    volumes:
      - custom_db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: mysecretpassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - custom_wordpress_data:/var/www/html

volumes:
  custom_db_data:
  custom_wordpress_data:
